framework:
    messenger:
        failure_transport: sync_products_failed

        transports:
            sync_products:
                dsn: 'amqp://rabbitmq:5672/%2f/sync_products'
                retry_strategy:
                    max_retries: 5
                    delay: 2000          # 2s initial delay
                    multiplier: 3        # 2s, 6s, 18s, 54s, 162s
                    max_delay: 600000    # cap at 10 min

            sync_products_failed:
                dsn: 'amqp://rabbitmq:5672/%2f/sync_products_failed'

        routing:
            App\Message\SyncProductMessage: sync_products
